name: Build

on: [ push, fork, pull_request ]

env:
  JAVA_VERSION: 1.11
  GRADLE_VERSION: 7.4

jobs:
  spotless-check:
    name: Spotless Apply

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Spotless Check - Gradle ${{ env.GRADLE_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: spotlessCheck

  javadocs-check:
    name: Javadocs

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Javadocs - Gradle ${{ env.GRADLE_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc

  final-build:
    name: Finalize

    needs:
      - spotless-check
      - javadocs-check

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build - Gradle ${{ env.GRADLE_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload ShrewsburyLib Build
        uses: actions/upload-artifact@v3
        with:
          name: ShrewsburyLib-Release
          path: ./build/libs/*.jar
          retention-days: 90
